import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";

const ppmori = localFont({
  src: [
    {
      path: "../public/fonts/PPMori-Regular.woff",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/PPMori-SemiBold.woff",
      weight: "600",
      style: "normal",
    },
  ],
  display: "swap",
  fallback: ["system-ui", "sans-serif"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={ppmori.className}>
      <body className="antialiased bg-[#FDFFFC] selection:bg-neutral-200/80 selection:text-neutral-400 md:text-lg">
        {children}
      </body>
    </html>
  );
}
